// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmsOzslFPf-_3X-x6d8gEiqAeFZAueKJE',
    appId: '1:227835713060:web:774f2a1d8af3b578d22ab1',
    messagingSenderId: '227835713060',
    projectId: 'fyp-fcm-656f5',
    authDomain: 'fyp-fcm-656f5.firebaseapp.com',
    storageBucket: 'fyp-fcm-656f5.firebasestorage.app',
    measurementId: 'G-C1QKZR9E83',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaKVl6eQ6IqvaA06IDyeBQJfbtP7qkaEg',
    appId: '1:227835713060:android:24bf930afdaed5bad22ab1',
    messagingSenderId: '227835713060',
    projectId: 'fyp-fcm-656f5',
    storageBucket: 'fyp-fcm-656f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqPmQKLSMSzbpdTW4ecbn27NN2rh88T-k',
    appId: '1:227835713060:ios:fcc7cd699cd72eead22ab1',
    messagingSenderId: '227835713060',
    projectId: 'fyp-fcm-656f5',
    storageBucket: 'fyp-fcm-656f5.firebasestorage.app',
    iosBundleId: 'com.example.fyp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmsOzslFPf-_3X-x6d8gEiqAeFZAueKJE',
    appId: '1:227835713060:web:e27b790c93a29e12d22ab1',
    messagingSenderId: '227835713060',
    projectId: 'fyp-fcm-656f5',
    authDomain: 'fyp-fcm-656f5.firebaseapp.com',
    storageBucket: 'fyp-fcm-656f5.firebasestorage.app',
    measurementId: 'G-215BPCJ7WH',
  );
}
